name: english_for_kids
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.3                     
  equatable: ^2.0.7               
  permission_handler: ^12.0.1     
  
  # Private Shared Package
  exo_shared:
    git:
      url: git@github.com:trungs99/exo_shared.git
      ref: v1.0.7

  cupertino_icons: ^1.0.8         
  google_fonts: ^6.2.1            
  flip_card: ^0.7.0               

  camera: ^0.11.3                 
  google_mlkit_image_labeling: ^0.14.1  

  flutter_tts: ^4.2.3             

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0           
  
  # Code Generation
  flutter_gen_runner: ^5.12.0     
  
  # Launcher Icon Generator (Chỉ dùng lúc dev)
  flutter_launcher_icons: ^0.14.4 


#  Config Assets Generation (FlutterGen)
flutter_gen:
  output: lib/gen/
  line_length: 150
  integrations:
    image: true
    flutter_svg: true
    rive: false
    lottie: false

# Run: dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  remove_alpha_ios: false
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon_app.png"
  image_path: "assets/images/icon_app.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/