name: english_for_kids
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  google_mlkit_image_labeling: ^0.14.1
  camera: ^0.11.3
  exo_shared:
    git:
      url: git@github.com:trungs99/exo_shared.git
      ref: v1.0.8
  flutter_tts: ^4.2.3
  get: ^4.7.3
  equatable: ^2.0.7
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_gen_runner: ^5.12.0
  isar_community_generator: ^3.3.0
  build_runner: ^2.7.1
  flutter_launcher_icons: ^0.14.4


flutter_gen:
  output: lib/gen/
  line_length: 150
  integrations:
    image: true
    flutter_svg: true
    rive: false
    lottie: false
# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/img_logo_app.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/img_logo_app.png"
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/learning/lession_1/
    - assets/images/topic/
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka_Condensed-Medium.ttf